### PR TITLE
sony: pioneer: audio: Increase speaker volume

### PR DESCRIPTION
**Pull request by pablomh**
Signed-off-by: Pablo Mendez Hernandez <pablomh@gmail.com>

### CODE REVIEW

**Comment by pablomh** [comment]
Ping @richardtullberg.

**Comment by luk1337** [comment]
This looks wrong, I don't think we should increase volumes for literally all usecases.

**Comment by pablomh** [comment]
In my experience the volume was low by default in every usecase I tried, but I can make it "finer-grained" if desired.

**Comment by pablomh** [comment]
I'll close while Richard works on this. Please check https://github.com/sonyxperiadev/device-sony-discovery/pull/17 for discussion about it.

**Pull request closed without merging**
